version: "3"

services:
  db:
    image: mongo
    volumes:
      - neat-code-volume:/data/db
    environment:
      MONGO_INITDB_DATABASE: neat
  bot:
    build: .
    volumes:
      - ./token:/app/token
    depends_on:
      - db
    links:
      - db
    dns:
      - 1.1.1.1
      - 1.0.0.1
volumes:
  neat-code-volume:
networks:
  default:
