version: "3"

services:
  db:
    image: mongo
    volumes:
      - neato-volume:/data/db
    environment:
      MONGO_INITDB_DATABASE: neat
  bot:
    build: .
    volumes:
      - ./discord-token:/app/discord-token
    depends_on:
      - db
    links:
      - db
    dns:
      - 1.1.1.1
      - 1.0.0.1
volumes:
  neato-volume:
networks:
  default:
